name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jeanlescure/react-deploy-to-s3-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        NODE_ENV: development # optional: defaults to production
        AWS_S3_BUCKET: react-chat-app
        AWS_ACCESS_KEY_ID: AKIAZPDRLJ7MQXAI75ME
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: us-east-1 # optional: defaults to us-east-1
        SOURCE_DIR: bundle # optional: defaults to public